#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v20
# autospec commit: f35655a
#
Name     : R-slam
Version  : 0.1.54
Release  : 62
URL      : https://cran.r-project.org/src/contrib/slam_0.1-54.tar.gz
Source0  : https://cran.r-project.org/src/contrib/slam_0.1-54.tar.gz
Summary  : Sparse Lightweight Arrays and Matrices
Group    : Development/Tools
License  : GPL-2.0
Requires: R-slam-lib = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
based on index arrays and simple triplet representations, respectively.

%package lib
Summary: lib components for the R-slam package.
Group: Libraries

%description lib
lib components for the R-slam package.


%prep
%setup -q -n slam
pushd ..
cp -a slam buildavx2
popd
pushd ..
cp -a slam buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1729089590

%install
export SOURCE_DATE_EPOCH=1729089590
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/slam/DESCRIPTION
/usr/lib64/R/library/slam/INDEX
/usr/lib64/R/library/slam/Meta/Rd.rds
/usr/lib64/R/library/slam/Meta/features.rds
/usr/lib64/R/library/slam/Meta/hsearch.rds
/usr/lib64/R/library/slam/Meta/links.rds
/usr/lib64/R/library/slam/Meta/nsInfo.rds
/usr/lib64/R/library/slam/Meta/package.rds
/usr/lib64/R/library/slam/NAMESPACE
/usr/lib64/R/library/slam/R/slam
/usr/lib64/R/library/slam/R/slam.rdb
/usr/lib64/R/library/slam/R/slam.rdx
/usr/lib64/R/library/slam/help/AnIndex
/usr/lib64/R/library/slam/help/aliases.rds
/usr/lib64/R/library/slam/help/paths.rds
/usr/lib64/R/library/slam/help/slam.rdb
/usr/lib64/R/library/slam/help/slam.rdx
/usr/lib64/R/library/slam/html/00Index.html
/usr/lib64/R/library/slam/html/R.css
/usr/lib64/R/library/slam/po/en@quot/LC_MESSAGES/R-slam.mo
/usr/lib64/R/library/slam/tests/abind.R
/usr/lib64/R/library/slam/tests/abind.Rout.save
/usr/lib64/R/library/slam/tests/apply.R
/usr/lib64/R/library/slam/tests/apply.Rout.save
/usr/lib64/R/library/slam/tests/crossprod.R
/usr/lib64/R/library/slam/tests/crossprod.Rout.save
/usr/lib64/R/library/slam/tests/dimgets.R
/usr/lib64/R/library/slam/tests/extract.R
/usr/lib64/R/library/slam/tests/extract.Rout.save
/usr/lib64/R/library/slam/tests/matrix.R
/usr/lib64/R/library/slam/tests/matrix.Rout.save
/usr/lib64/R/library/slam/tests/matrix_dimnames.R
/usr/lib64/R/library/slam/tests/matrix_dimnames.Rout.save
/usr/lib64/R/library/slam/tests/rollup.R
/usr/lib64/R/library/slam/tests/rollup.Rout.save
/usr/lib64/R/library/slam/tests/split.R
/usr/lib64/R/library/slam/tests/split.Rout.save
/usr/lib64/R/library/slam/tests/ssa_valid.R
/usr/lib64/R/library/slam/tests/ssa_valid.Rout.save
/usr/lib64/R/library/slam/tests/stm.R
/usr/lib64/R/library/slam/tests/stm.Rout.save
/usr/lib64/R/library/slam/tests/stm_apply.R
/usr/lib64/R/library/slam/tests/stm_apply.Rout.save
/usr/lib64/R/library/slam/tests/stm_rollup.R
/usr/lib64/R/library/slam/tests/stm_rollup.Rout.save
/usr/lib64/R/library/slam/tests/stm_subassign.R
/usr/lib64/R/library/slam/tests/stm_subassign.Rout.save
/usr/lib64/R/library/slam/tests/stm_ttcrossprod.R
/usr/lib64/R/library/slam/tests/stm_ttcrossprod.Rout.save
/usr/lib64/R/library/slam/tests/stm_valid.R
/usr/lib64/R/library/slam/tests/stm_valid.Rout.save
/usr/lib64/R/library/slam/tests/stm_zeros.R
/usr/lib64/R/library/slam/tests/stm_zeros.Rout.save
/usr/lib64/R/library/slam/tests/subassign.R
/usr/lib64/R/library/slam/tests/subassign.Rout.save
/usr/lib64/R/library/slam/tests/util.R
/usr/lib64/R/library/slam/tests/util.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/slam/libs/slam.so
/V4/usr/lib64/R/library/slam/libs/slam.so
/usr/lib64/R/library/slam/libs/slam.so
